name: Comprehensive CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Run CI Pipeline
    strategy:
      matrix:
        runner: [self-hosted, ubuntu-latest] # Prefer self-hosted, fallback to GitHub-hosted runner
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    steps:
      # Step 1: Clone the Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7  # Use Python 3.12.7 for the project

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy nltk langdetect pandas spacy pytest pytest-cov pytest-mock pgmpy tensorflow torch transformers pytorch torchvision torchaudio emoji
     
      # Step 5: Cache Dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Test Linting
      - name: Run Linting
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Test Dependency Security Vulnerabilities
      - name: Check Dependency Security Vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          args: check --full-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Test Application Security Vulnerabilities
      - name: Run Bandit Security Checks
        uses: pycqa/bandit-action@v1.2.0
        with:
          args: -r models/base_models

      # Step 7: Run Unit Tests and Generate Coverage Report
      - name: Run Unit Tests
        run: |
          pytest --cov=. --cov-report=json
