name: Comprehensive CI Pipeline

on:
  push:
    branches:
      - '**' # Trigger on all branches
  pull_request:
    branches:
      - '**' # Trigger on all branches
    types:
    - opened
    - reopened
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  ci:
    name: Run CI Pipeline
    strategy:
      matrix:
        runner: [ubuntu-latest] # GitHub-hosted runner
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    steps:
      # Step 1: Clone the Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7  # Use Python 3.12.7 for the project

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Test Linting
      - name: Run Linting
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Test Dependency Security Vulnerabilities
      - name: Check Dependency Security Vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          args: check --full-report
          api-key: ${{ secrets.SAFETY_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Test Application Security Vulnerabilities
      - name: Run Bandit Security Checks
        uses: pycqa/bandit-action@v1.0.0
        with:
          args: -r models/base_models
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Run Unit Tests and Generate Coverage Report
      - name: Run Unit Tests
        run: |
          pytest --cov=. --cov-report=json
